---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: api-whatcheese-web-vs
  namespace: whatcheese
spec:
  tls:
    secret: whatcheese-cert
  host: "api.whatcheese.nginx.demo"
  #policies:
  #  - name: cheese-waf
  routes:
  - path: /
    route: api-whatcheese-routes
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: www-whatcheese-web-vs
  namespace: whatcheese
spec:
  host: "www.whatcheese.nginx.demo"
  tls:
    secret: whatcheese-cert
  upstreams:
  - name: webv1
    service: whatcheese-web
    port: 80
  - name: webv2
    service: whatcheese-web-v2
    port: 80
  #policies:
  #  - name: cheese-waf
  routes:
  - path: /
    matches:
    - conditions:
      - cookie: austin
        value: yeahBabyYeah
      action:
        pass: webv2
    action:
      pass:  webv1
