---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatcheese-web
  namespace: whatcheese
  labels:
    app: whatcheese-web
spec:
  selector:
    matchLabels:
      app: whatcheese-web
  replicas: 2
  template:
    metadata:
      labels:
        app: whatcheese-web
    spec:
      serviceAccount: cheese-web-sa
      containers:
      - name: whatcheese-web
        image: tuxinvader/whatcheese-web:ocp
        imagePullPolicy: Always
        ports:
#        - containerPort: 443
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: whatcheese-web
  namespace: whatcheese
spec:
  selector:
    app: whatcheese-web
  #type: NodePort
  type: ClusterIP
  clusterIP: None
  ports:
#    - name: https
#      port: 443
#      targetPort: 443
#      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
