---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: api-whatcheese-web-vs
  namespace: whatcheese
spec:
  host: api.cheese.apps-crc.testing
  tls:
    secret: whatcheese-cert
  upstreams:
  - name: apiv1
    service: whatcheese-api
    port: 80
  routes:
  - path: /
    action:
      proxy:
        upstream: apiv1
        responseHeaders:
          add: 
          - name: "Access-Control-Allow-Origin"
            value: "*"
            always: true
          - name: "X-Your-IP"
            value: "${remote_addr}"
            always: true
  - path: /v1/add
    matches:
    - conditions:
      - argument: psk 
        value: superSecretKey
      action:
        proxy:
          upstream: apiv1
          responseHeaders:
            add: 
            - name: "Access-Control-Allow-Origin"
              value: "*"
              always: true
    action:
      return:
        code: 200
        type: application/json
        body: |
          {\"result\": \"ERROR\", \"details\": \"Please provide the Super Secret Key in the psk field\"}
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: www-whatcheese-web-vs
  namespace: whatcheese
spec:
  host: www.cheese.apps-crc.testing
  tls:
    secret: whatcheese-cert
  upstreams:
  - name: webv1
    service: whatcheese-web
    port: 80
  - name: webv2
    service: whatcheese-web-v2
    port: 80
  routes:
  - path: /
    matches:
    - conditions:
      - cookie: austin
        value: yeahBabyYeah
      action:
        pass: webv2
    action:
      pass:  webv1
