---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: api-whatcheese-web-vs
  namespace: whatcheese
spec:
  host: api.cheese.apps-crc.testing
  tls:
    secret: whatcheese-cert
  policies:
    - name: cheese-waf
  upstreams:
  - name: apiv1
    service: whatcheese-api
    port: 80
  routes:
  - path: /
    route: api-whatcheese-routes
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: www-whatcheese-web-vs
  namespace: whatcheese
spec:
  host: www.cheese.apps-crc.testing
  tls:
    secret: whatcheese-cert
  policies:
    - name: cheese-waf
  upstreams:
  - name: webv1
    service: whatcheese-web
    port: 80
  - name: webv2
    service: whatcheese-web-v2
    port: 80
  routes:
  - path: /
    matches:
    - conditions:
      - cookie: austin
        value: yeahBabyYeah
      action:
        pass: webv2
    action:
      pass:  webv1
