---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: api-whatcheese-routes
  namespace: whatcheese
spec:
  host: "api.cheese.apps-crc.testing"
  upstreams:
  - name: apiv1
    service: whatcheese-api
    port: 80
  subroutes:
  - path: /
    action:
      proxy:
        upstream: apiv1
        responseHeaders:
          add:
          - name: "Access-Control-Allow-Origin"
            value: "*"
            always: true
          - name: "X-Your-IP"
            value: "${remote_addr}"
            always: true
        requestHeaders:
          add:
          - name: "X-Forwarded-Proto"
            value: "${scheme}"
  - path: /v1/add
    matches:
    - conditions:
      - argument: psk
        value: superSecretKey
      action:
        proxy:
          upstream: apiv1
          responseHeaders:
            add:
            - name: "Access-Control-Allow-Origin"
              value: "*"
              always: true
          requestHeaders:
            add:
            - name: "X-Forwarded-Proto"
              value: "${scheme}"
    action:
      return:
        code: 200
        type: application/json
        body: |
          {\"result\": \"ERROR\", \"details\": \"Please provide the Super Secret Key in the psk field\"}

